# Generated by Django 3.2.8 on 2022-01-31 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Username', models.CharField(max_length=50, verbose_name='admin username')),
                ('Admin_Password', models.CharField(max_length=50, verbose_name='admin password')),
            ],
        ),
        migrations.CreateModel(
            name='deliveryrecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_item_name', models.CharField(max_length=50, verbose_name='delivery_item_name')),
                ('delivery_unit', models.CharField(max_length=50, verbose_name='delivery_unit')),
                ('delivery_description', models.CharField(max_length=50, verbose_name='delivery_description')),
                ('delivery_quantity', models.CharField(max_length=50, verbose_name='delivery_quantity')),
                ('delivery_remaining', models.CharField(max_length=50, verbose_name='delivery_remaining')),
                ('current_date', models.DateField(default=datetime.date.today, verbose_name='delivery_current_date')),
            ],
            options={
                'db_table': 'deliveryrecords',
            },
        ),
        migrations.CreateModel(
            name='limitrecords',
            fields=[
                ('limit_id', models.AutoField(primary_key=True, serialize=False)),
                ('limit_item_name', models.CharField(max_length=50, verbose_name='limit_item_name')),
                ('limit_quantity', models.CharField(max_length=50, verbose_name='limit_quantity')),
                ('limit_unit', models.CharField(max_length=50, verbose_name='limit_unit')),
                ('limit_department', models.CharField(max_length=50, verbose_name='limit_department')),
                ('limit_code', models.CharField(max_length=50, verbose_name='limit_code')),
            ],
            options={
                'db_table': 'limitrecords',
            },
        ),
        migrations.CreateModel(
            name='mainstorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='ItemName')),
                ('Unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='Quantity')),
                ('Remaining', models.CharField(max_length=50, verbose_name='Remaining')),
            ],
            options={
                'db_table': 'mainstorage',
            },
        ),
        migrations.CreateModel(
            name='withdrawrecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_item_name', models.CharField(max_length=50, verbose_name='withdraw__item_name')),
                ('withdraw_unit', models.CharField(max_length=50, verbose_name='withdraw_unit')),
                ('withdraw_quantity', models.CharField(max_length=50, verbose_name='withdraw_quantity')),
                ('current_date', models.DateField(default=datetime.date.today, verbose_name='withdraw_current_date')),
                ('withdraw_department', models.CharField(max_length=50, verbose_name='withdraw_department')),
            ],
            options={
                'db_table': 'withdrawrecords',
            },
        ),
    ]
