# Generated by Django 3.2.9 on 2021-11-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='withdrawpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Records_of_Delivery', models.CharField(max_length=50, verbose_name='records of delivery')),
                ('PreWithdraw_of_Records', models.CharField(max_length=50, verbose_name='pre withdraw of records')),
                ('Records_of_Withdraw', models.CharField(max_length=50, verbose_name='records of withdraw')),
            ],
        ),
    ]
