# Generated by Django 3.2.8 on 2021-12-27 13:27

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyDept_Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='limitrecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_item_name', models.CharField(max_length=50, verbose_name='limit_department')),
                ('limit_unit', models.CharField(max_length=50, verbose_name='limit_unit')),
                ('limit_quantity', models.CharField(max_length=50, verbose_name='limit_quantity')),
                ('limit_remaining', models.CharField(max_length=50, verbose_name='limit_remaining')),
                ('limit_date', models.DateField(default=datetime.date.today, verbose_name='limit_current_date')),
                ('limit_time', models.TimeField(default=django.utils.timezone.now, verbose_name='limit_current_date')),
            ],
            options={
                'db_table': 'limitrecords',
            },
        ),
    ]
