# Generated by Django 3.2.9 on 2021-11-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyDept_Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverypage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Records_of_Delivery', models.CharField(max_length=50, verbose_name='records of delivery')),
            ],
        ),
        migrations.CreateModel(
            name='statuspage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryRecords', models.CharField(max_length=50, verbose_name='delivery records')),
                ('request_of_limit', models.CharField(max_length=50, verbose_name='request of limits')),
            ],
        ),
        migrations.RenameField(
            model_name='withdrawpage',
            old_name='PreWithdraw_of_Records',
            new_name='prewithdraw_of_records',
        ),
        migrations.RenameField(
            model_name='withdrawpage',
            old_name='Records_of_Delivery',
            new_name='records_of_delivery',
        ),
        migrations.RenameField(
            model_name='withdrawpage',
            old_name='Records_of_Withdraw',
            new_name='records_of_withdraw',
        ),
    ]
