# Generated by Django 3.2.8 on 2021-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyDept_Inventory', '0002_limitrecords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitrecords',
            name='limit_date',
        ),
        migrations.RemoveField(
            model_name='limitrecords',
            name='limit_remaining',
        ),
        migrations.RemoveField(
            model_name='limitrecords',
            name='limit_time',
        ),
        migrations.AddField(
            model_name='limitrecords',
            name='limit_department',
            field=models.CharField(default=50, max_length=50, verbose_name='limit_department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='limitrecords',
            name='limit_item_name',
            field=models.CharField(max_length=50, verbose_name='limit_item_name'),
        ),
    ]
