# Generated by Django 3.2.8 on 2021-12-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyDept_Inventory', '0003_auto_20211209_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrecords',
            name='current_date',
            field=models.DateField(max_length=50, verbose_name='withdraw_current_date'),
        ),
        migrations.AlterField(
            model_name='withdrawrecords',
            name='current_time',
            field=models.TimeField(max_length=50, verbose_name='withdarw_current_time'),
        ),
    ]
