# Generated by Django 3.2.9 on 2021-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyDept_Inventory', '0003_auto_20211125_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCS_CASHIER_SERVICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='OES_EXTENSION_SERVICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='OGS_GUIDANCE_SERVICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='OHR_HUMAN_RESOURCES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
    ]
