# Generated by Django 3.2.8 on 2022-01-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyDept_Inventory', '0004_mainstorage_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrecords',
            name='withdraw_department',
            field=models.CharField(default=50, max_length=50, verbose_name='withdraw_department'),
            preserve_default=False,
        ),
    ]
