# Generated by Django 3.2.9 on 2021-11-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyDept_Inventory', '0004_ocs_cashier_services_oes_extension_services_ogs_guidance_services_ohr_human_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHS_HEALTH_SERVICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='OIT_INFORMATION_TECHNOLOGY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='OPR_PROCUREMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='ORE_RESEARCH_AND_EXTENSION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='ORM_RECORD_MANAGEMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='ORS_RESEARCH_SERVICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='OSP_JOB_PLACEMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50, verbose_name='item name')),
                ('Unit', models.CharField(max_length=50, verbose_name='unit')),
                ('Quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryrecords',
            name='current_date',
            field=models.DateField(max_length=50, verbose_name='current date'),
        ),
        migrations.AlterField(
            model_name='deliveryrecords',
            name='current_time',
            field=models.TimeField(max_length=50, verbose_name='current time'),
        ),
        migrations.AlterField(
            model_name='withdrawrecords',
            name='current_date',
            field=models.DateField(max_length=50, verbose_name='current date'),
        ),
        migrations.AlterField(
            model_name='withdrawrecords',
            name='current_time',
            field=models.TimeField(max_length=50, verbose_name='current time'),
        ),
        migrations.AlterModelTable(
            name='deliveryrecords',
            table='deliveryrecords',
        ),
        migrations.AlterModelTable(
            name='mainstorage',
            table='mainstorage',
        ),
        migrations.AlterModelTable(
            name='withdrawrecords',
            table='withdrawrecords',
        ),
    ]
