# Generated by Django 3.2.8 on 2021-12-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyDept_Inventory', '0004_ocs_cashier_services_oes_extension_services_ogs_guidance_services_ohr_human_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryrecords',
            old_name='delivery_current_date',
            new_name='current_date',
        ),
        migrations.RenameField(
            model_name='deliveryrecords',
            old_name='delivery_current_time',
            new_name='current_time',
        ),
        migrations.AlterField(
            model_name='deliveryrecords',
            name='delivery_item_name',
            field=models.CharField(max_length=50, verbose_name='delivery_item_name'),
        ),
        migrations.AlterField(
            model_name='deliveryrecords',
            name='delivery_quantity',
            field=models.CharField(max_length=50, verbose_name='delivery_quantity'),
        ),
        migrations.AlterField(
            model_name='deliveryrecords',
            name='delivery_unit',
            field=models.CharField(max_length=50, verbose_name='delivery_unit'),
        ),
        migrations.AlterModelTable(
            name='deliveryrecords',
            table='deliveryrecords',
        ),
    ]
